name: Docker Build And Push CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (v1.0.6)'
        required: true


env:
  GCP_PID: ${{ secrets.GCP_PID }}
  REGISTRY: 'europe-west1-docker.pkg.dev'
  REGISTRY_USERNAME: '_json_key'
  REGISTRY_PASSWORD: ${{ secrets.GCP_CICD_KEY }}
  REGISTRY_NAME: 'utl-api'

jobs:
#
#  test:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install modules
#      run: npm i
#    - name: Run tests
#      run: npm run test:detect

  docker-push-api:
#    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
          images: | # used as base name for tags ;)
            ${{ env.REGISTRY }}/${{ env.GCP_PID }}/${{ env.REGISTRY_NAME }}/base-production
          tags: |
            type=semver,pattern={{version}}   
            type=raw,value={{branch}}-sha-{{sha}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          provenance: false
          cache-to: type=gha,mode=max
          file: '_docker/base.Dockerfile'
          tags: '${{ steps.meta.outputs.tags }}'
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            START_CMD=tail -f /dev/null
